--- !<tag:framesquared.com,2015:config>
paths:
  migrations dir: ../migrations
  migrations file: ../migrations/migrationData.json
  meta dir: ../metadata
sequence:
  merge:
    columns: name
actions:
  create table:
  - action: generate
    inga: templates/tf/tf_model_cpp.inja
    data: target
    out: models/{{ uCamel(create table) }}.cpp
    overwrite: true
  - action: generate
    inga: templates/tf/tf_model_h.inja
    data: target
    out: models/{{ uCamel(create table) }}.h
    overwrite: true
  - action: generate
    inga: templates/tf/tf_sqlobject.inja
    data: target
    out: models/sqlobjects/{{ uCamel(create table) }}.h
    overwrite: true
  alter table:
  - inga: ../templates/tf/alter.inja
    data: patch
    out: alter.txt
    overwrite: true
map:
  db_type:
    string: character varying
    numeric: double
    timestamp: timestamp without time zone
    boolean: int
  extjs_type:
    uuid: string
  qt_type:
    uuid: QString
    string: QString
    timestamp: QDateTime