--- !<tag:framesquared.com,2015:config>
paths:
  migrations: ../migrations
template:
  create table:
    logged: true
    temporary: false
    columns: []
sequence:
  merge:
    columns: name
map:
  db_type:
    string: character varying
    numeric: double
    timestamp: timestamp without time zone
    boolean: int
  extjs_type:
    uuid: string
  qt_type:
    uuid: QString
    string: QString
    timestamp: QDateTime