--- !<tag:framesquared.com,2015:config>
paths:
  migrations: ../migrations
  meta: ../metadata
template:
  create table:
    logged: true
    temporary: false
    columns: []
sequence:
  merge:
    columns: name
genertor:
  create table:
  - inga: path_to_inja_file
    data: patch
    out: /path/to/output/{{ file_name }}.ext
  - inga: path_to_inja_file
    data: patch
    out: /path/to/output/{{ file_name }}.ext
map:
  db_type:
    string: character varying
    numeric: double
    timestamp: timestamp without time zone
    boolean: int
  extjs_type:
    uuid: string
  qt_type:
    uuid: QString
    string: QString
    timestamp: QDateTime