mysql_db_type:
  string:	varchar
  integer:	int
  float:	float
  double:	double
  numeric:	decimal
  boolean:	boolean
  uuid:	    uuid
  ubigint:	bigint unsigned
  serial:	bigint unsigned
  date: 	datetime
extjs_type:
  uuid: string
qt_type:
  string:   QString
  integer:  int
  float:    double
  double:   double
  numeric:  double
  boolean:  char
  uuid:     uuid
  ubigint:  qulonglong
  serial:   qulonglong
  date:     QDateTime
qt_qvariant:
  string:   "{{ lCamel(name) }}"
  integer:  "{{ lCamel(name) }}.toInt()"
  float:    "{{ lCamel(name) }}.toDouble()"
  double:   "{{ lCamel(name) }}.toDouble()"
  numeric:  "{{ lCamel(name) }}.toDouble()"
  uuid:     "uuid_xyzzy"
  ubigint:  "{{ lCamel(name) }}.toULongLong()"
  serial:   "{{ lCamel(name) }}.toULongLong()"
  date:     "QDateTime::fromString({{ lCamel(name) }})"
exclude:
  created_at: true
  updated_at: true
  modified_at: true
  lock_revision: true
  createdAt: true
  updatedAt: true
  modifiedAt: true
  lockRevision: true

