mysql_db_type:
  string:	varchar
  integer:	int
  float:	float
  double:	double
  numeric:	decimal
  boolean:	boolean
  uuid:	uuid
  ubigint:	bigint(20) unsigned
  datetime:	datetime
extjs_type:
  uuid: string
qt_type:
  string: QString
  integer: int
  float: double
  double: double
  numeric: double
  boolean: char
  uuid: uuid
  ubigint: qtulonglong
  datetime: QDateTime