mysql_db_type:
  string:	varchar
  integer:	int
  float:	float
  double:	double
  numeric:	decimal
  boolean:	boolean
  uuid:	varchar
  serial:	serial
  datetime:	datetime
extjs_type:
  uuid: string
qt_type:
  string: QString
  integer: int
  float: double
  double: double
  numeric: double
  boolean: char
  uuid: varchar
  serial: int
  datetime: QDateTime